### ISSUE TITLE
Can't init. Ensure that BOOT0 is enabled and reset device

### ISSUE THREAD

**Issue by ferazambuja** [Altitude-Tech/Sensly_Install#4]
I'm trying to install it. Did the calibration using the file on the Sensy git, since there is no file on this distro. The i2c address shows with no problem. 

Here is the log for ./update.sh
`Can't init. Ensure that BOOT0 is enabled and reset device
Traceback (most recent call last):
  File "stm32loader.py", line 436, in <module>
    bootversion = cmd.cmdGet()
  File "stm32loader.py", line 118, in cmdGet
    if self.cmdGeneric(0x00):
  File "stm32loader.py", line 115, in cmdGeneric
    return self._wait_for_ask(hex(cmd))
  File "stm32loader.py", line 80, in _wait_for_ask
    raise CmdException("Can't read port or timeout")
__main__.CmdException: Can't read port or timeout
`

From lsusb
`Bus 001 Device 009: ID 0483:df11 STMicroelectronics STM Device in DFU Mode
Bus 001 Device 005: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

From dfu-util
`dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Found DFU: [0483:df11] ver=2200, devnum=9, cfg=1, intf=0, path="1-1.3", alt=1, name="@Option Bytes  /0x1FFFF800/01*016 e", serial="FFFFFFFEFFFF"
Found DFU: [0483:df11] ver=2200, devnum=9, cfg=1, intf=0, path="1-1.3", alt=0, name="@Internal Flash  /0x08000000/064*0002Kg", serial="FFFFFFFEFFFF"`

**Comment by duchenef** [comment]
Same issue for me
