### ISSUE TITLE
Issue i2cdetect and unable to run Update.sh

### ISSUE THREAD

**Issue by teokino** [Altitude-Tech/Sensly_Install#5]
Hello!
I have  a Raspberry Pi 3 Model B with only Sensly connected.
As you can see from the attached image, "i2cdetect -y 1" I got strange results after many attempts every 5 seconds. 

Even the script Update.sh has some problems. Similar to what was said by other users, the script entered in a infinite waiting. Checking and running its source code, I have tried to test it separately thus I got:

"_sudo python stm32loader.py -e -w -v -p /dev/ttyS0 -b 115200 Sensly.binary_" ---> [Errno 2] could not open port /dev/ttyS0: [Errno 2] No such file or directory: '/dev/ttyS0'.

For clarity "_ls -l /dev/ttyS0_" give me an error.

Instead the second command placed in "OR" sudo "_python stm32loader.py -e -w -v -p /dev/ttyAMA0 -b 115200 Sensly.binary_" is fine. As you can see:
"_ls -l /dev/ttyAMA0_" ---> crw-rw---- 1 root dialout 204, 64 apr  6 15:27 /dev/ttyAMA0

Anyway the last command crashes at line #109 of "stm32loader.py" (self.sp.write("\x7F")).

Did any of you have had similar problems?

![2018-04-06-163119](https://user-images.githubusercontent.com/38206859/38492814-7088f622-3bf0-11e8-93a9-d32b9188e9e6.jpg)

**Comment by phgachoud** [comment]
I did not remember where but somebody from altitudeTech said me that the update.sh never worked... what is your purpose to do with this script???

I get also these strange responses from i2detect actually it seems that its not only your HAT that makes that. I also tried a Pi2 & Pi3 and same result. (Hint you can do something like watch -n2 i2cdetect -y 1 to look @ the results every 2 secs)

**Comment by teokino** [comment]
Thanks for the tip on the script. I wanted to be able to run Update.sh because it is written on the installation guide that it is necessary to do so in order to exit the calibration mode. Acquiring data with Sensly.py I get all values in 0. Instead, using the image provided by Alittude Tech I get different values, strange but certainly not zero.

**Comment by phgachoud** [comment]
@teokino if you encounter the same issue than me, please lets follow on Sensly project with issue 1

It seems that the update.sh doesn't work and isn't necessary either. As far as I remember I could get some values from some sensors but they are rounded to zero from a function [according to this issue ](https://github.com/Altitude-Tech/Sensly/issues/1)

Could you please post the link of the image provided by Altitude Tech?

Tryout my https://github.com/phgachoud/Sensly/tree/sensors_tests (branch sensors_tests) Which is the latest logging version. Got some datas from over there, you can see a logging file as example in this repo/branch

**Comment by teokino** [comment]
@phgachoud I have found the image searching in several forums. The link is: [https://download.altitude.tech/Sensly/](url). The "stable" folder is empty, instead in "dev" there is a .zip image. This image it seems works, at least the values are not zeros but I think that is very old (I don't remeber which version of kernel).

Any of you know why running `i2cdetect -y 1` I got some strange 07 and 08 positions? I haven't any other devices connected to Raspberry Pi 3 Model B+.

**Comment by Sam-AlteredCarbon** [comment]
Hi, I will be uploading a modified version of the Update script that should work, please test it and let me know any issues you have.

**Comment by phgachoud** [comment]
@samAlti please let it into the git repository so people can get it from there!

**Comment by 2Dman** [comment]
agreed, running the update.sh script gives me the following errors:

sudo sh Update.sh 
Traceback (most recent call last):
  File "stm32loader.py", line 427, in <module>
    cmd.open(conf['port'], conf['baud'])
  File "stm32loader.py", line 71, in open
    timeout=5               # set a timeout value, None for waiting forever
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 315, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
Can't init. Ensure that BOOT0 is enabled and reset device
Traceback (most recent call last):
  File "stm32loader.py", line 436, in <module>
    bootversion = cmd.cmdGet()
  File "stm32loader.py", line 118, in cmdGet
    if self.cmdGeneric(0x00):
  File "stm32loader.py", line 115, in cmdGeneric
    return self._wait_for_ask(hex(cmd))
  File "stm32loader.py", line 80, in _wait_for_ask
    raise CmdException("Can't read port or timeout")
__main__.CmdException: Can't read port or timeout

**Comment by ferazambuja** [comment]
I have the same issue. The STM32 get's in DFU mode, you can check by plugging the USB port on the HAT. It's even possible to flash using dfu-util. However, I don't know how the binary file works.
